bar:
    - seperator: " | "

modules:
    - cpu: active
      position: 0
      prefix: 'CPU '
      args: [0.2]

    - mem: active
      position: 1
      prefix: 'RAM '

    - datetime: active
      position: 2
      args: ['Europe/London', '%d/%m/%Y %I:%M %p']

      # Read https://docs.python.org/3/library/datetime.html?highlight=datetime#strftime-and-strptime-format-codes
      # for format code
